version: 0.0
os: linux
files:
  - source:  /
    destination: /home/hospital/apache-tomcat-8.5.57/webapps

permissions:
  - object: /
    pattern: "**"
    owner: hospital
    group: hospital

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user